# Dev properties with DEBUG logging level.

server:
  port: 5990
service:
  jwtValidator:
    domain: http://localhost:5980
    validationUrl: /api/auth/token/validate
  jwtSecret: secretsecretsecretsecretsecretsecretsecret
  tokenPrefix: msvc_
  spotify:
    name: SPOTIFY
    pageSize: 50
    urls:
      domain: https://api.spotify.com
      likedTracks: /v1/me/tracks
      likeTrack: /v1/me/tracks
      searchTrack: /v1/search
      playlists: /v1/me/playlists
      playlistTracks: /v1/playlists/{id}/tracks
      me: /v1/me
      createPlaylist: /v1/users/{user-id}/playlists
  ytmusic:
    name: YT_MUSIC
    pageSize: 50
    urls:
      domain: https://www.googleapis.com
      likedTracks: /youtube/v3/videos
      playlists: /youtube/v3/playlists
      playlistTracks: /youtube/v3/playlistItems
circuitBreaker:
  minimumNumberOfCalls: 3
  slidingWindowSize: 80
  failureRateThreshold: 70.0
retry:
  attempts: 2
  windowSeconds: 2
logging:
  level:
    com.mf.api: DEBUG
management:
  endpoint:
    health:
      probes:
        enabled: true
swagger:
  url: /swagger-ui/index.html
  title: Music Transfer API [DEBUG PROFILE]
  description: Music Transfer API
  version: "1.0.0-SNAPSHOT"
  controllersPackage: com.mf.api.adapter.in.rest
