# Dev properties with DEBUG logging info.
#
# Set params
#     service.spotify.clientId
#     service.spotify.clientSecret
#     service.ytmusic.clientId
#     service.ytmusic.clientSecret
#
# or environment variables
#     SERVICE_SPOTIFY_CLIENTID
#     SERVICE_SPOTIFY_CLIENTSECRET
#     SERVICE_YTMUSIC_CLIENTID
#     SERVICE_YTMUSIC_CLIENTSECRET


server:
  port: 5980
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mf?createDatabaseIfNotExist=true
    username: root
    password: docker
  sql:
    init:
      mode: always
service:
  encryptionAlgName: AES
  encryptionKeySize: 16
  encryptionTransformation: AES/CBC/PKCS5Padding
  uuidSecret: secretsecretsecretsecretsecretsecretsecret
  jwtIssuer: auth-service
  jwtSecret: secretsecretsecretsecretsecretsecretsecret
  jwtExpirationSeconds: 7200
  uuidExpirationSeconds: 7200
  accessTokenExpirationSeconds: 7200
  spotify:
    name: SPOTIFY
    clientScope: 'user-library-read user-library-modify playlist-read-private
      playlist-modify-public playlist-modify-private'
    grantType: authorization_code
    clientRedirectUrl: http://localhost:5980/api/auth/spotify/callback
    urls:
      auth: https://accounts.spotify.com/authorize
      token: https://accounts.spotify.com/api/token
  ytmusic:
    name: YT_MUSIC
    clientScope: 'https://www.googleapis.com/auth/youtube.readonly 
    https://www.googleapis.com/auth/youtube.upload'
    grantType: authorization_code
    clientRedirectUrl: http://localhost:5980/api/auth/ytmusic/callback
    urls:
      auth: https://accounts.google.com/o/oauth2/v2/auth
      token: https://oauth2.googleapis.com/token
logging:
  level:
    com.mf.auth: DEBUG
management:
  endpoint:
    health:
      probes:
        enabled: true
swagger:
  url: /swagger-ui/index.html
  title: Auth API [DEBUG PROFILE]
  description: Authentication API
  version: "1.0.0-SNAPSHOT"
  controllersPackage: com.mf.auth.adapter.in.rest
