logging:
  level:
    com.mf.serviceconfig: INFO
management:
  endpoint:
    health:
      probes:
        enabled: true
swagger:
  url: /swagger-ui/index.html
  controllersPackage: com.mf.serviceconfig.rest
